/*
 * ConsultarVendas.java
 *
 * Created on 2 de Fevereiro de 2008, 00:47
 */

package br.com.sisvenda;

import br.com.sisvenda.vendas.VendasBean;
import br.com.sisvenda.vendas.VendasControl;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;

/**
 *
 * @author  Cláudio
 */
public class ConsultarVendas extends javax.swing.JFrame {
    
    DefaultTableModel tmVendas = new DefaultTableModel(null, new String[] {"Código da Venda","Cód Produto","Produto","Cód Cliente","Cliente", "Quantidade", "Data"});
    List<VendasBean> vendas;
    
    /** Creates new form ConsultarVendas */
    public ConsultarVendas() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVendas = new javax.swing.JTable();
        ftfDataInicio = new com.toedter.calendar.JDateChooser();
        ftfDataFim = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Vendas");

        jLabel1.setText("Data Inicial:");

        jLabel2.setText("Data Final:");

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        tbVendas.setModel(tmVendas);
        jScrollPane1.setViewportView(tbVendas);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setText("Consultar Vendas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(253, 253, 253))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 767, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(8, 8, 8)
                        .addComponent(ftfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(ftfDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ftfDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel2)
                        .addComponent(ftfDataInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        pesquisarVendas();
    }//GEN-LAST:event_btPesquisarActionPerformed
    
    private void pesquisarVendas(){
        VendasControl vc = new VendasControl();
        if (ftfDataInicio.getDate() == null){
            JOptionPane.showMessageDialog(this, "Informe a data Inicial!");
            ftfDataInicio.requestFocus();
        } else if (ftfDataFim.getDate() == null){
            JOptionPane.showMessageDialog(this, "Informe a data Final!");
            ftfDataFim.requestFocus();
        } else {
            while (tmVendas.getRowCount() > 0){
                tmVendas.removeRow(0);
            }
            
            SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date dataInicio = (java.util.Date) ftfDataInicio.getDate();
            System.out.println(formato.format(dataInicio));
            java.util.Date dataFim = (java.util.Date) ftfDataFim.getDate();
            vendas = vc.listarVendas(Date.valueOf(formato.format(dataInicio)), Date.valueOf(formato.format(dataFim)));
            String [] campos = new String[] {null, null, null, null, null,null,null};
            for (int i = 0; i < vendas.size(); i++){
                tmVendas.addRow(campos);
                tmVendas.setValueAt(vendas.get(i).getCodigo(), i, 0);
                tmVendas.setValueAt(vendas.get(i).getCodigoProduto(), i, 1);
                tmVendas.setValueAt(vendas.get(i).getNomeProduto(), i, 2);
                tmVendas.setValueAt(vendas.get(i).getCodigoCliente(), i, 3);
                tmVendas.setValueAt(vendas.get(i).getNomeCliente(), i, 4);
                tmVendas.setValueAt(vendas.get(i).getQuantidade(), i, 5);
                tmVendas.setValueAt(vendas.get(i).getDataVenda(), i, 6);
            }
            if (vendas.size() == 0){
                JOptionPane.showMessageDialog(this, "Nenhum registro encontrado!");
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarVendas().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private com.toedter.calendar.JDateChooser ftfDataFim;
    private com.toedter.calendar.JDateChooser ftfDataInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbVendas;
    // End of variables declaration//GEN-END:variables
    
}
