/*
 * Fornecedores.java
 *
 * Created on 24 de Janeiro de 2008, 23:33
 */

package br.com.sisvenda;

import br.com.sisvenda.acessobd.AcessoMySql;
import br.com.sisvenda.clientes.ClienteBean;
import br.com.sisvenda.clientes.ClienteControl;
import br.com.sisvenda.fornecedores.FornecedorBean;
import br.com.sisvenda.fornecedores.FornecedorControl;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author  Cláudio
 */
public class FornecedoresOld extends javax.swing.JFrame {
    DefaultTableModel tmFornecedores = new DefaultTableModel(null, new String[]{"Código", "Nome", "Endereço", "Telefone"});
    ListSelectionModel lsmFornecedores;
    List<FornecedorBean> fornecedores;
    String tipoCadastro;
    java.sql.PreparedStatement pstm;
    ResultSet rs;
    /** Creates new form Fornecedores */
    public FornecedoresOld() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfPesquisaFornecedor = new javax.swing.JTextField();
        btPesquisarFornecedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFornecedores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfEndereco = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        tfUf = new javax.swing.JTextField();
        tfCep = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JTextField();
        btNovo = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();

        setTitle("Fornecedores");

        btPesquisarFornecedor.setText("Pesquisar");
        btPesquisarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarFornecedorActionPerformed(evt);
            }
        });

        tbFornecedores.setModel(tmFornecedores);
        tbFornecedores.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmFornecedores = tbFornecedores.getSelectionModel();
        lsmFornecedores.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (! e.getValueIsAdjusting()){
                    tbFornecedoresLinhaSelecionada(tbFornecedores);
                }
            }
        });
        jScrollPane1.setViewportView(tbFornecedores);

        jLabel1.setText("Nome:");

        tfNome.setEditable(false);

        jLabel2.setText("Endereço:");

        jLabel3.setText("Bairro:");

        tfEndereco.setEditable(false);

        tfBairro.setEditable(false);

        jLabel4.setText("Cidade:");

        jLabel5.setText("UF:");

        jLabel6.setText("CEP:");

        jLabel7.setText("Telefone:");

        tfCidade.setEditable(false);

        tfUf.setEditable(false);

        tfCep.setEditable(false);

        tfTelefone.setEditable(false);

        btNovo.setText("Novo");
        btNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");

        btFechar.setText("Fechar");

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Filtrar Por:");

        cb2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Codigo", "Nome" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel10.setText("Fornecedores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(btNovo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btAlterar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btCancelar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btFechar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(tfEndereco)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGap(220, 220, 220)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(tfTelefone))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addGap(95, 95, 95)
                                            .addComponent(jLabel7)
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(tfUf, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(329, 329, 329))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfPesquisaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btPesquisarFornecedor))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(126, 126, 126)
                                            .addComponent(jLabel5))
                                        .addComponent(jLabel2))
                                    .addGap(0, 0, Short.MAX_VALUE))))))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAlterar, btCancelar, btFechar, btNovo, btPesquisarFornecedor});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btPesquisarFornecedor)
                    .addComponent(tfPesquisaFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNovo)
                    .addComponent(btAlterar)
                    .addComponent(btCancelar)
                    .addComponent(btFechar)
                    .addComponent(jButton1))
                .addGap(47, 47, 47))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAlterar, btCancelar, btFechar, btNovo, btPesquisarFornecedor});

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoActionPerformed
        novoFornecedor();
    }//GEN-LAST:event_btNovoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       cadastraFornecedor();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btPesquisarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarFornecedorActionPerformed
       listarFornecedor();
    }//GEN-LAST:event_btPesquisarFornecedorActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
       
         alterarFornecedor();
    }//GEN-LAST:event_btAlterarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FornecedoresOld().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btFechar;
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btPesquisarFornecedor;
    private javax.swing.JComboBox cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbFornecedores;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCep;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfEndereco;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPesquisaFornecedor;
    private javax.swing.JTextField tfTelefone;
    private javax.swing.JTextField tfUf;
    // End of variables declaration//GEN-END:variables
    
    private void alteraFornecedor(){
        if (tbFornecedores.getSelectedRow() != -1){
            habilitarCampos();
        } else{
            JOptionPane.showMessageDialog(this, "Selecione um cliente!");
        }
    }
    
    protected boolean verificarUF(){
        if (tfUf.getText().length() > 2)
            return false;
        return true;
    }
    
      protected void alterarFornecedor(){
        if (verificarCampos() && verificarUF()){
            FornecedorBean fornecedor = new FornecedorBean();
            fornecedor.setCodigo(fornecedores.get(tbFornecedores.getSelectedRow()).getCodigo());
            fornecedor.setNome(tfNome.getText().trim());
            fornecedor.setEndereco(tfEndereco.getText().trim());
            fornecedor.setBairro(tfBairro.getText().trim());
            fornecedor.setCidade(tfCidade.getText().trim());
            fornecedor.setUf(tfUf.getText().trim());
            fornecedor.setCep(tfCep.getText().trim());
            fornecedor.setTelefone(tfTelefone.getText().trim());
            FornecedorControl c = new FornecedorControl();
            c.alterarFornecedor(fornecedor);
            desabilitarCampos();
        } else{
            JOptionPane.showMessageDialog(this, "Informe o nome do cliente!");
            tfNome.requestFocus();
        }
    }
    
    protected void tbFornecedoresLinhaSelecionada(JTable tb){
        if (tb.getSelectedRow() != -1){
            tfNome.setText(fornecedores.get(tb.getSelectedRow()).getNome());
            tfEndereco.setText(fornecedores.get(tb.getSelectedRow()).getEndereco());
            tfBairro.setText(fornecedores.get(tb.getSelectedRow()).getBairro());
            tfCidade.setText(fornecedores.get(tb.getSelectedRow()).getCidade());
            tfUf.setText(fornecedores.get(tb.getSelectedRow()).getUf());
            tfCep.setText(fornecedores.get(tb.getSelectedRow()).getCep());
            tfTelefone.setText(fornecedores.get(tb.getSelectedRow()).getTelefone());
        } else {
            tfNome.setText("");
            tfEndereco.setText("");
            tfCidade.setText("");
            tfBairro.setText("");
            tfUf.setText("");
            tfCep.setText("");
            tfTelefone.setText("");
        }
    }
    
     private void novoFornecedor(){
        habilitarCampos();
        tfNome.setText("");
        tfEndereco.setText("");
        tfCidade.setText("");
        tfBairro.setText("");
        tfUf.setText("");
        tfCep.setText("");
        tfTelefone.setText("");
    }
    
     protected void cadastraFornecedor(){
        if (verificarCampos() && verificarUF()){
            FornecedorBean fornecedor = new FornecedorBean();
            fornecedor.setNome(tfNome.getText().trim());
            fornecedor.setEndereco(tfEndereco.getText().trim());
            fornecedor.setBairro(tfBairro.getText().trim());
            fornecedor.setCidade(tfCidade.getText().trim());
            fornecedor.setUf(tfUf.getText().trim());
            fornecedor.setCep(tfCep.getText().trim());
            fornecedor.setTelefone(tfTelefone.getText().trim());
            FornecedorControl c = new FornecedorControl();
            c.cadastrarFornecedor(fornecedor);
            desabilitarCampos();
        }
    }
    
     
     
     protected boolean verificarCampos(){
        if (!tfNome.getText().trim().equals("")){
            return true;
        }
        return false;
    }
     
     
     private void habilitarCampos(){
        tfNome.setEditable(true);
        tfEndereco.setEditable(true);
        tfBairro.setEditable(true);
        tfCidade.setEditable(true);
        tfCep.setEditable(true);
        tfUf.setEditable(true);
        tfTelefone.setEditable(true);
    
    }
    
    protected void desabilitarCampos(){
        tfNome.setEditable(false);
        tfEndereco.setEditable(false);
        tfBairro.setEditable(false);
        tfCidade.setEditable(false);
        tfCep.setEditable(false);
        tfUf.setEditable(false);
        tfTelefone.setEditable(false);
       
    }
    
    
     protected void listarFornecedor(){
        FornecedorControl cli = new FornecedorControl();
        fornecedores = cli.listarFornecedores("%" + tfPesquisaFornecedor.getText().trim() + "%");
        mostrarFornecedor(fornecedores);
    }
     
     
     protected void mostrarFornecedor(List<FornecedorBean> fornecedores){
        while (tmFornecedores.getRowCount() > 0){
           tmFornecedores.removeRow(0);
        }
        
        if (fornecedores.size() == 0){
            JOptionPane.showMessageDialog(this, "Nenhum cliente encontrado!");
        }else{
            String [] campos = new String[] {null, null, null, null};
            for (int i = 0; i < fornecedores.size(); i++){
               tmFornecedores.addRow(campos);
               tmFornecedores.setValueAt(fornecedores.get(i).getCodigo(), i, 0);
               tmFornecedores.setValueAt(fornecedores.get(i).getNome(), i, 1);
               tmFornecedores.setValueAt(fornecedores.get(i).getEndereco(), i, 2);
               tmFornecedores.setValueAt(fornecedores.get(i).getTelefone(), i, 3);
            }
        }
    }
     
     
     public void pesquisarUsuarios()
     {
         
           if(cb2.getSelectedItem().equals("Codigo")){
         String sql = "Select *from fornecedor where codigo like ?";
         try
         {
           AcessoMySql mysql= new AcessoMySql();
           pstm = mysql.conectar().prepareStatement(sql);
           pstm.setString(1,tfPesquisaFornecedor.getText()+"%");
           rs = pstm.executeQuery();
           tbFornecedores.setModel(DbUtils.resultSetToTableModel(rs));
           
         }
         catch(SQLException error)
         {
            JOptionPane.showMessageDialog(null, error);
         }
     }
           
           
           if(cb2.getSelectedItem().equals("Nome")){
         String sql = "Select *from fornecedor where nome like ?";
         try
         {
           AcessoMySql mysql= new AcessoMySql();
           pstm = mysql.conectar().prepareStatement(sql);
           pstm.setString(1,tfPesquisaFornecedor.getText()+"%");
           rs = pstm.executeQuery();
           tbFornecedores.setModel(DbUtils.resultSetToTableModel(rs));
           
         }
         catch(SQLException error)
         {
            JOptionPane.showMessageDialog(null, error);
         }
     }
           
     }
     
}
