/*
 * Principal.java
 *
 * Created on 17 de Janeiro de 2008, 23:44
 */

package br.com.sisvenda;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author  Cláudio
 */
public class Principal extends javax.swing.JFrame {
    
    /** Creates new form Principal */
    public Principal() {
        initComponents();
    }
    
    Clientes clientes;
    RegistrarVenda produtos;
    FornecedoresOld fornecedores;
    Produtos registraVenda;
    ConsultarVendas consultaVenda;
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btClientes = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btFornecedores = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btConsultarVenda = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btProdutos = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuOpcoes = new javax.swing.JMenu();
        mnuSobre = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mnuSair = new javax.swing.JMenuItem();
        mnuCadastros = new javax.swing.JMenu();
        mnuClientes = new javax.swing.JMenuItem();
        mnuFornecedores = new javax.swing.JMenuItem();
        mnuRegistrarVenda = new javax.swing.JMenuItem();
        mnuVendas = new javax.swing.JMenu();
        mnuConsultarVenda = new javax.swing.JMenuItem();
        mnuProdutos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Vendas");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btClientes.setText("Clientes");
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btClientes);
        jToolBar1.add(jSeparator2);

        btFornecedores.setText("Fornecedores");
        btFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedoresActionPerformed(evt);
            }
        });
        jToolBar1.add(btFornecedores);
        jToolBar1.add(jSeparator3);

        btConsultarVenda.setText("Consultar Vendas");
        btConsultarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarVendaActionPerformed(evt);
            }
        });
        jToolBar1.add(btConsultarVenda);
        jToolBar1.add(jSeparator4);

        btProdutos.setText("Vendas");
        btProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(btProdutos);
        jToolBar1.add(jSeparator5);

        jButton1.setText("Produtos");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        mnuOpcoes.setText("Opções");

        mnuSobre.setText("Sobre o Sistema...");
        mnuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSobreActionPerformed(evt);
            }
        });
        mnuOpcoes.add(mnuSobre);
        mnuOpcoes.add(jSeparator1);

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuOpcoes.add(mnuSair);

        jMenuBar1.add(mnuOpcoes);

        mnuCadastros.setText("Cadastros");

        mnuClientes.setText("Clientes");
        mnuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuClientesActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuClientes);

        mnuFornecedores.setText("Fornecedores");
        mnuFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFornecedoresActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuFornecedores);

        mnuRegistrarVenda.setText("Produtos");
        mnuRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegistrarVendaActionPerformed(evt);
            }
        });
        mnuCadastros.add(mnuRegistrarVenda);

        jMenuBar1.add(mnuCadastros);

        mnuVendas.setText("Vendas");

        mnuConsultarVenda.setText("Consultar");
        mnuConsultarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultarVendaActionPerformed(evt);
            }
        });
        mnuVendas.add(mnuConsultarVenda);

        mnuProdutos.setText("Vendas");
        mnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutosActionPerformed(evt);
            }
        });
        mnuVendas.add(mnuProdutos);

        jMenuBar1.add(mnuVendas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1003, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 500, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void mostraConsultaVenda(){
        if (consultaVenda == null){
            consultaVenda = new ConsultarVendas();
            consultaVenda.setVisible(true);
        } else{
            consultaVenda.setVisible(true);
            consultaVenda.setState(JFrame.NORMAL);
        }
    }
    
    private void btConsultarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarVendaActionPerformed
        mostraConsultaVenda();
    }//GEN-LAST:event_btConsultarVendaActionPerformed
        private void mostraRegistroVenda(){
        if (registraVenda == null){
            registraVenda = new Produtos();
            registraVenda.setVisible(true);
        } else{
            registraVenda.setVisible(true);
            registraVenda.setState(JFrame.NORMAL);
        }
    }
            
    private void mostraFornecedores(){
        if (fornecedores == null){
            fornecedores = new FornecedoresOld();
            fornecedores.setVisible(true);
        } else{
            fornecedores.setVisible(true);
            fornecedores.setState(JFrame.NORMAL);
        }
    }
    
    private void btFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedoresActionPerformed
        mostraFornecedores();
    }//GEN-LAST:event_btFornecedoresActionPerformed
    
    private void btProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutosActionPerformed
        mostraProdutos();
    }//GEN-LAST:event_btProdutosActionPerformed
    
    private void mostraProdutos(){
        if (produtos == null){
            produtos = new RegistrarVenda();
            produtos.setVisible(true);
        } else{
            produtos.setVisible(true);
            produtos.setState(JFrame.NORMAL);
        }
        
    }
        
    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        mostrarClientes();
    }//GEN-LAST:event_btClientesActionPerformed

    private void mnuConsultarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultarVendaActionPerformed
        mostraConsultaVenda();
    }//GEN-LAST:event_mnuConsultarVendaActionPerformed

    private void mnuRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegistrarVendaActionPerformed
        mostraRegistroVenda();
    }//GEN-LAST:event_mnuRegistrarVendaActionPerformed

    private void mnuFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFornecedoresActionPerformed
        mostraFornecedores();
    }//GEN-LAST:event_mnuFornecedoresActionPerformed

    private void mnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutosActionPerformed
       RegistrarVenda o = new RegistrarVenda();
       o.setVisible(true);
    }//GEN-LAST:event_mnuProdutosActionPerformed

    private void mnuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuClientesActionPerformed
        mostrarClientes();
    }//GEN-LAST:event_mnuClientesActionPerformed

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        sair();
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSobreActionPerformed
        JOptionPane.showMessageDialog(null, "Sistema de Vendas - www.t2ti.com");
    }//GEN-LAST:event_mnuSobreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   mostraRegistroVenda();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void mostrarClientes(){
        if (clientes == null){
            clientes = new Clientes();
            clientes.setVisible(true);
        } else{
            clientes.setVisible(true);
            clientes.setState(JFrame.NORMAL);
        }
    }
            
    private void sair(){
        System.exit(0);
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btConsultarVenda;
    private javax.swing.JButton btFornecedores;
    private javax.swing.JButton btProdutos;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mnuCadastros;
    private javax.swing.JMenuItem mnuClientes;
    private javax.swing.JMenuItem mnuConsultarVenda;
    private javax.swing.JMenuItem mnuFornecedores;
    private javax.swing.JMenu mnuOpcoes;
    private javax.swing.JMenuItem mnuProdutos;
    private javax.swing.JMenuItem mnuRegistrarVenda;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenuItem mnuSobre;
    private javax.swing.JMenu mnuVendas;
    // End of variables declaration//GEN-END:variables
    
}
